[package]
name = "overload"
version = "0.1.0"
authors = ["Md Sarowar Alam <sarowar.cse@gmail.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/eipi1/overload"
description = """
An util to overload API with requests
"""
categories = ["development-tools"]
keywords = ["load-testing", "cluster"]

[lib]
name = "overload"
path = "src/overload/lib.rs"

[dependencies.rust-cloud-discovery]
version = "0.1"
optional = true

[dependencies.cloud-discovery-kubernetes]
version = "0.1"
optional = true

[dependencies.cluster-mode]
version = "0.1"
optional = true

[dependencies.bytes]
version = "1.0"

[dependencies.lazy_static]
version = "1.4"

[dependencies.futures-util]
version = "0.3"

[dependencies.pin-project]
version = "1.0"

[dependencies.tokio]
version = "1.4"
features = ["rt-multi-thread", "macros"]

[dependencies.tokio-stream]
version = "0.1"

[dependencies.http]
version = "0.2"

[dependencies.hyper]
version = "0.14"
features = ["runtime", "http1", "http2", "client", "stream"]

[dependencies.warp]
version = "0.3"

[dependencies.regex]
version = "1.4"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.serde_json]
version = "1.0"

[dependencies.http-serde]
version = "1.0"

[dependencies.uuid]
version = "0.8"
features = ["v4"]

[dependencies.rand]
version = "0.8"

[dependencies.anyhow]
version = "1.0"

[dependencies.cfg-if]
version = "1.0"

[dependencies.prometheus]
version = "0.12"

[dependencies.log]
version = "0.4"

[dependencies.tracing]
version = "0.1"

[dependencies.tracing-subscriber]
version = "0.2"

[dev-dependencies.tokio-test]
version = "0.4"

[features]
default = ["debug"]

cluster = ["rust-cloud-discovery", "cloud-discovery-kubernetes", "cluster-mode"]
# addtional checks for debugging/logging purpose
debug = []
