[package]
name = "overload"
version = "0.1.0"
authors = ["sarowar <sarowar.cse@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#[[bin]]
#name="scribble_1"
#path = "scribbles/s1.rs"
#required-features= ["runtime"]

#[features]
#default = []
#default = ["cluster", "mock"]

#cluster = []
#mock = []

[lib]
name = "overload"
path = "src/overload/lib.rs"
#[lib]
#name = "http"
#path = "src/http/lib.rs"

[dependencies]
tokio = { version = "1.2", features = ["full", "time", "sync", "macros"] }
tokio-stream = { version="0.1.3", features=["time"] }
futures = "0.3"
futures-util = "0.3"
hyper = { version = "0.14", features = ["runtime"] }
rand = "0.8"
chrono = "0.4"
rand_distr = "0.2"
serde = { version = "1.0", features = ["derive", "std", "rc"] }
rmp-serde = "0.14"
tracing = "0.1"
tracing-futures = "0.2"
tracing-subscriber = { version = "0.2", features = ["fmt"] }
async-trait = "0.1"
url = { version = "2.1", features = ["serde"] }
bytes = "1.0"
serde_json = "1.0"
evmap = "10.0"
warp = "0.3"
strum = "0.18"
strum_macros = "0.18"
uuid = { version = "0.8", features = ["v4", "serde"] }
pin-project-lite = "0.2"
prometheus = "0.9"
lazy_static = "1.4"
tdigest = "0.2"
arc-swap = "0.4"
kube = "0.39"
k8s-openapi = { version = "0.9", features=["v1_18"] }
tokio-test = "0.4.0"
http = "0.2"
evmap-derive = "0.1"
headers = "0.3"
hyper-tls = "0.4"
native-tls = "0.2"
#tokio-tls = "0.3"
#actix-broker = "0.3"
config = "0.10"