[workspace]
members = [
    "overload",
    "response-assert",
    "cluster-executor",
    "overload-http",
    "datagen",
    "overload-metrics",
    "lua-helper",
    "tests"
]

[profile.release]
debug = true
