{
 "title": "overload-ks",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": "label_values(upstream_request_count{job=~\"overload|overload-k8s\"},job_id)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(upstream_request_count{job=~\"overload|overload-k8s\", job_id=\"$job\"},instance)"
   }
  ]
 },
 "panels": [
  { "title": "RPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job_id) (rate(upstream_request_count{job_id=\"${job}\"}[1m]))",
     "legendFormat": "Total RPS"
    }
   ]
  },
  {
   "title": "Response Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(upstream_request_status_count{job_id=\"${job}\"}[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "RPS per pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(upstream_request_count{job_id=\"${job}\"}[1m])",
     "legendFormat": "RPS - {{instance}}"
    }
   ]
  },
  { "title": "Response Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Avg Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(rate(upstream_response_time_sum{job_id=\"${job}\"}[1m])/rate(upstream_response_time_count{job_id=\"${job}\"}[1m]))",
     "legendFormat": "Response time"
    }
   ]
  },
  {
   "title": "Response Time - Percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(upstream_response_time_bucket{job_id=\"${job}\"}[1m])) by (le))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(upstream_response_time_bucket{job_id=\"${job}\"}[1m])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(upstream_response_time_bucket{job_id=\"${job}\"}[1m])) by (le))",
     "legendFormat": "75th"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(upstream_response_time_bucket{job_id=\"${job}\"}[1m])) by (le))",
     "legendFormat": "50th"
    }
   ]
  },
  { "title": "Connection - $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }, "repeat": "instance" },
  {
   "title": "Connection Pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "connection_pool_new_connection_attempt{job_id=\"${job}\", instance=~\"$instance\"}",
     "legendFormat": "Attempt"
    },
    {
     "expr": "connection_pool_new_connection_success{job_id=\"${job}\", instance=~\"$instance\"}",
     "legendFormat": "Success"
    },
    {
     "expr": "-(connection_pool_connection_broken{job_id=\"${job}\", instance=~\"$instance\"})",
     "legendFormat": "broken"
    },
    {
     "expr": "-(connection_pool_connection_dropped{job_id=\"${job}\", instance=~\"$instance\"})",
     "legendFormat": "dropped"
    }
   ]
  },
  {
   "title": "Connection Pool - rates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(connection_pool_new_connection_attempt{job_id=\"${job}\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "Attempt"
    },
    {
     "expr": "irate(connection_pool_new_connection_success{job_id=\"${job}\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "Success"
    },
    {
     "expr": "-irate(connection_pool_connection_broken{job_id=\"${job}\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "broken"
    },
    {
     "expr": "-irate(connection_pool_connection_dropped{job_id=\"${job}\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "dropped"
    }
   ]
  },
  {
   "title": "Connection Pool - Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "connection_pool_new_connection_success{job_id=\"${job}\", instance=~\"$instance\"}-connection_pool_connection_dropped{job_id=\"${job}\", instance=~\"$instance\"}",
     "legendFormat": "Active connection"
    },
    {
     "expr": "connection_pool_size{job_id=\"${job}\", instance=~\"$instance\"}",
     "legendFormat": "Pool size"
    }
   ]
  },
  {
   "title": "Connection Pool - Busy/idle",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "connection_pool_connection_idle{job_id=\"${job}\", instance=~\"$instance\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "connection_pool_connection_busy{job_id=\"${job}\", instance=~\"$instance\"}",
     "legendFormat": "Busy"
    }
   ]
  },
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=~\"overload.*\"}[1m])*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Open File Descriptor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=~\"overload.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"overload.*\"}",
     "legendFormat": "RES - {{instance}}"
    }
   ]
  }
 ]
}