{
 "title": "Overload",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": "label_values(upstream_request_count{job=~\"overload|overload-k8s\"},job_id)"
   }
  ]
 },
 "panels": [
  { "title": "RPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job_id) (rate(upstream_request_count{job_id=\"${job}\"}[1m]))",
     "legendFormat": "Total RPS"
    }
   ]
  },
  {
   "title": "Response Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(upstream_request_status_count{job_id=\"${job}\"}[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "Response Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Avg Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(upstream_response_time_sum{job_id=\"${job}\"}[1m])/rate(upstream_response_time_count{job_id=\"${job}\"}[1m]))",
     "legendFormat": "Response time"
    }
   ]
  },
  {
   "title": "Response Time - Percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(upstream_response_time_bucket{job_id=\"${job}\"}[1m])) by (le))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(upstream_response_time_bucket{job_id=\"${job}\"}[1m])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(upstream_response_time_bucket{job_id=\"${job}\"}[1m])) by (le))",
     "legendFormat": "75th"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(upstream_response_time_bucket{job_id=\"${job}\"}[1m])) by (le))",
     "legendFormat": "50th"
    }
   ]
  }
 ]
}