name: Dockerhub

on:
  push:
    branches: [ master ]
  release:
    types: [published]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests for cluster
      run: cargo test --features="cluster" --verbose
    - name: Get version
      run: |
        if [[ ${{ github.event_name }} == 'release' ]]; then
            PKG_VERSION=$(cargo pkgid | cut -d# -f2)
            TAG_VERSION=${GITHUB_REF:11}
            if [[ $PKG_VERSION != $TAG_VERSION ]]; then
                echo "::error::version mismatch: pkg=$PKG_VERSION, tag=$GITHUB_REF"
                exit 1
            fi
            echo "version=$PKG_VERSION" >> "$GITHUB_ENV"
            echo "suffix=" >> "$GITHUB_ENV"
        else
            echo "version=latest" >> "$GITHUB_ENV"
            echo "suffix=-snapshot" >> "$GITHUB_ENV"
        fi
    - name: Build cluster
      run: cargo build --bins --features "cluster" --release
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Build cluster image
      uses: docker/build-push-action@v2.5.0
      with:
        context: .
        push: true
        tags: mdsarowar/overload:${{ env.version }}-cluster${{ env.suffix }}
    - name: Run standalone tests
      run: cargo test --verbose
    - name: Build standalone
      run: cargo build --bins --release
    - name: Build & push standalone image
      uses: docker/build-push-action@v2.5.0
      with:
        context: .
        push: true
        tags: mdsarowar/overload:${{ env.version }}-standalone${{ env.suffix }}
