name: Dockerhub

on:
  workflow_run:
    workflows: ["Rust"]
    types: [completed]
    branches: [ main ]
  release:
    types: [published]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Get version
      run: |
        if [[ ${{ github.event_name }} == 'release' ]]; then
            cargo generate-lockfile
            PKG_VERSION=$(cargo pkgid -p file://$(pwd)/overload | cut -d# -f2)
            TAG_VERSION=${GITHUB_REF:11}
            if [[ $PKG_VERSION != $TAG_VERSION ]]; then
                echo "::error::version mismatch: pkg=$PKG_VERSION, tag=$GITHUB_REF"
                exit 1
            fi
            echo "version=$PKG_VERSION" >> "$GITHUB_ENV"
            echo "suffix=" >> "$GITHUB_ENV"
        else
            echo "version=latest" >> "$GITHUB_ENV"
            echo "suffix=-snapshot" >> "$GITHUB_ENV"
        fi
    - name: Login to Github Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build & push standalone image
      uses: docker/build-push-action@v7
      with:
        context: .
        file: standalone.Dockerfile
        push: true
        tags:
          ghcr.io/${{ github.repository }}:standalone-${{ env.version }}${{ env.suffix }}
    - name: Build cluster image
      uses: docker/build-push-action@v7
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository }}:cluster-${{ env.version }}${{ env.suffix }}
