name: Dockerhub

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --bin --features "cluster" --release
    - name: Run tests
      run: cargo test --verbose
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Build cluster image
      uses: docker/build-push-action@v2.5.0
      with:
        context: .
        push: true
        tags: mdsarowar/overload:latest-cluster-snapshot
    - name: Build standalone
      run: cargo build --bin --release
    - name: Build & push standalone image
      uses: docker/build-push-action@v2.5.0
      with:
        context: .
        push: true
        tags: mdsarowar/overload:latest-standalone-snapshot
