name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - name: install lua
      run: sudo apt install -y liblua5.3-dev
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up cargo cache
      uses: actions/cache@v3
      continue-on-error: false
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-
    - name: Lint
      run: cargo fmt --all -- --check
    - name: Run cluster tests
      run: cargo test --all-features -- --list --format=terse && RUST_BACKTRACE=1 cargo test --all-features -- --test-threads=1 --show-output
    - name: Install mdbook
      run: |
        mkdir bin
        curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.21/mdbook-v0.4.21-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=bin
        echo "$(pwd)/bin" >> $GITHUB_PATH
    - name: Install mdbook-lintcheck
      run: |
        cd bin && \
        curl -L https://github.com/Michael-F-Bryan/mdbook-linkcheck/releases/latest/download/mdbook-linkcheck.x86_64-unknown-linux-gnu.zip -o mdbook-linkcheck.zip && \
        unzip "$_" && \
        chmod +x mdbook-linkcheck && \
        cd ..
    - name: Test mdBook
      run: |
        rm ./target/debug/deps/liboverload_http-*
        rm ./target/debug/deps/libserde_json-*
        rm ./target/debug/deps/libresponse_assert-*
        cargo build -p overload-http --all-features
        mdbook test docs -L ./target/debug/deps/
    - name: build mdBook
      run: mdbook build docs/
    - name: Run standalone tests
      run: cargo test
